### ISSUE TITLE
Can you add the option to bind the home button to return to yuno?

### ISSUE THREAD

**Issue by azeemhub123** [Flutterando/yuno#17]
On daijisho there is an option to bind the home button so when you press it, it returns to daijisho instead of the main android frontend. If we could have it for yuno it would be a great quality of life feature

**Comment by jacobaraujo7** [comment]
Hello. Thanks for the question.
Today there is the possibility of replacing the main launcher with YuNO, making the home button return to yuno.
It is in our plans, but we disable it until we are out of the early stages of development.
We will soon have this function.
Thanks.
