### ISSUE TITLE
Update the main GitHub page with a user guide

### ISSUE THREAD

**Issue by azeemhub123** [Flutterando/yuno#18]
Mainly a guide for setting up vita as I have no idea how to do it. If vita is not supported, could it be removed from the list of platforms to avoid confusion.

**Comment by jacobaraujo7** [comment]
Hello. Vita has standardization problems with all frontends, but everything will be resolved soon.
As we are in Alpha, there is no problem in maintaining the Vita, but if the problems are not resolved by the release candidate then we will have to remove it.
