### ISSUE TITLE
Use controllers to navigate in "Apps" and "Settings"

### ISSUE THREAD

**Issue by Panzarin** [Flutterando/yuno#9]
Like the title says, would be nice to navigate in those sections using physical controllers. Right now we can only navigate through touch input.

**Comment by jacobaraujo7** [comment]
Hello.
Thanks for the sugestion.
I imagined that the apps part would be better for gestures, but it makes sense to have the controls there, I'll implement it.

**Comment by jacobaraujo7** [comment]
Added controls on the apps page.
On the settings page it will take a little longer.
